<?php
/** @var Lightna\Engine\Data\Url $url */
?>
<link rel="preload" as="font" crossorigin="anonymous"
      href="<?= $url->asset('lightna/magento-os-frontend/font/Assistant/Assistant-ExtraLight.woff2') ?>"/>
<link rel="preload" as="font" crossorigin="anonymous"
      href="<?= $url->asset('lightna/magento-os-frontend/font/Assistant/Assistant-Regular.woff2') ?>"/>
<link rel="preload" as="font" crossorigin="anonymous"
      href="<?= $url->asset('lightna/magento-os-frontend/font/Assistant/Assistant-SemiBold.woff2') ?>"/>
