<div class="search__close" data-click-action="close-search">
    <span class="icon icon-arrow-left"></span>
</div>
<form action="/catalogsearch/result/" class="cjs-search">
    <div class="search__input">
        <button class="search__submit-btn btn-reset btn-disabled"
                type="submit"
                title="<?= phrase('Search') ?>">
            <span class="icon icon-search"></span>
        </button>
        <input type="search" name="q" id="search" value="" minlength="3" maxlength="128" class="search__input-field"
               placeholder="<?= phrase('Search entire store here...') ?>" autocomplete="off">
        <button class="search__clear-btn btn-reset hidden"
                type="reset"
                data-click-action="clear-search"
                title="<?= phrase('Clear') ?>">
            <span class="icon icon-close icon-close-xs"></span>
        </button>
    </div>
</form>
