<?php
/** @var Lightna\Magento\Frontend\Data\Block $block */
/** @var Lightna\Magento\Data\Session $session */
/** @var Lightna\Engine\Data\Request $request */

if (!$request->isPost) {
    return;
}
$cart = $session->cart;
?>
<div <?= $block->attributes() ?> <?= $block->hiThere() ?>>
    <div class="overlay__title__container">
        <span class="overlay__title"><?= phrase('Your Cart') ?></span>
        <!-- Close minicart -->
        <div class="icon" data-action="close-minicart"></div>
    </div>
    <?php if ($cart->qty === 0): ?>
        <?= block('empty') ?>
    <?php else: ?>
        <?= block('products') ?>
        <?= block('footer') ?>
    <?php endif; ?>
</div>
