<?php
/** @var Lightna\Engine\Data\Block $block */
?>
<header>
    <div class="header__container">
        <!-- Open mobile menu -->
        <div class="cjs-toggle-overlay header__open-menu" data-overlay="menu"></div>
        <!-- Logo -->
        <?php block('logo') ?>
        <!-- Menu -->
        <?php block('menu') ?>
        <!-- Search -->
        <div class="header__right">
            <!-- Account -->
            <!-- Wishlist -->
            <!-- Minicart -->
            <?php block('minicart') ?>
        </div>
    </div>
</header>
