<?php
$serverTime = round((microtime(true) - $GLOBALS['LIGHTNA_START_TIME']) * 1000, 2);
$elasticTime = round(Lightna\Elasticsearch\App\Client::$timeSpent * 1000, 2);
?>
<script>
    const serverTime = <?= escape($serverTime, 'json-js') ?>;
    const elasticTime = <?= escape($elasticTime, 'json-js') ?>;
    const el = document.getElementById('serverTime');
    const mode = window.pageContext?.mode;
    const modeText = mode === '' ? 'Lightna' : window.pageContext.laneDemoMode;

    el.innerHTML = '[' + modeText + '] Server rendering time: ' + serverTime + 'ms';
    if (elasticTime) {
        el.innerHTML += ' (incl. Elasticsearch: ' + elasticTime + 'ms)';
    }
</script>
