<?php
/**
 * Import:
 * @var Lightna\Magento\Data\Config $config
 */

$ga = $config->ga;
if (!$ga->active || !$ga->account) {
    return;
}
?>
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
            new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
        j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
        'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','<?= $ga->account('url-param') ?>');</script>
<!-- End Google Tag Manager -->
