cli:
  command:
    build.asset.sign: Lightna\Engine\App\Console\Asset\Sign
    config.apply: Lightna\Engine\App\Console\Config\Apply
    update: Lightna\Engine\App\Console\Update
    index.update.opcache: Lightna\Engine\App\Console\Index\Update\Opcache
    index.update.data: Lightna\Engine\App\Console\Index\Update\Data
    index.update.all: Lightna\Engine\App\Console\Index\Update\All
    index.queue.process: Lightna\Engine\App\Console\Index\Queue\Process
    index.queue.watch: Lightna\Engine\App\Console\Index\Queue\Watch
    index.queue.block: Lightna\Engine\App\Console\Index\Queue\Block
    index.queue.unblock: Lightna\Engine\App\Console\Index\Queue\Unblock
    index.queue.reset: Lightna\Engine\App\Console\Index\Queue\Reset
    index.version.bind: Lightna\Engine\App\Console\Index\Version\Bind
    index.version.next: Lightna\Engine\App\Console\Index\Version\Next
    index.version.previous: Lightna\Engine\App\Console\Index\Version\Previous
    index.gc: Lightna\Engine\App\Console\Index\Gc
    entity.show: Lightna\Engine\App\Console\Entity\Show
    opcache.slap: Lightna\Engine\App\Console\Opcache\Slap
  update:
    - Lightna\Engine\App\Update\Schema\Index\Changelog
    - Lightna\Engine\App\Update\Schema\Index\Triggers
    - Lightna\Engine\App\Update\Schema\Index\Queue
    - Lightna\Engine\App\Update\Schema\Storage\Database
