indexer:
  changelog:
    tables: [ ]
    batch:
      collectors: [ ]
  watch:
    start_at: 5
    interval: 2
    stop_at: 50
  queue:
    lock_wait_interval_ms: 250
    lock_wait_print_interval: 5
    allowed_check_interval_ms: 250
