<div class="dropdown__wrap">
    <div class="dropdown__content dropdown__content--guest">
        <p>
            <?= phrase('Create an account or login to see your orders and personal information.') ?>
        </p>
        <div class="dropdown__buttons">
            <a class="btn btn-ghost" href="/customer/account/create" title="<?= phrase('Register') ?>">
                <span><?= phrase('Register') ?></span>
            </a>
            <a class="btn" href="/customer/account/" title="<?= phrase('Login') ?>">
                <span><?= phrase('Login') ?></span>
            </a>
        </div>
    </div>
</div>
