<?php
/**
 * Import:
 * @var Lightna\Engine\Data\Request $request
 * @var array $messages
 */
if (!$request->isPost) {
    return;
}
?>
<?php foreach ($messages as $message): ?>
    <div class="message <?= escape($message['type']) ?> fade-in">
        <div class="message__content">
            <span>
                <?= /* @noEscape */ $message['text'] ?>
            </span>
        </div>
        <div class="message__close"></div>
    </div>
<?php endforeach; ?>
