<?php
/**
 * Import:
 * @var Lightna\Engine\Data\Url $url
 * @var Lightna\Magento\Backend\Data\Product\Search $search
 */

$pageCount = ceil($search->total / $search->pageSize);
$currentPage = $search->currentPage;
if ($pageCount <= 1) {
    return;
}
?>
<nav class="pagination">
    <ul class="pagination__list">
        <li class="pagination__item pagination__item--prev <?= $currentPage === 1 ? 'pagination__item--disabled' : '' ?>">
            <a class="pagination__link" href="<?= escape($url->current(['p' => $currentPage - 1])) ?>">
                <span class="icon icon-arrow-left"></span>
            </a>
        </li>
        <?php foreach ($search->getPagination() as $pageNum => $pageLabel) { ?>
            <li class="pagination__item <?= $currentPage === $pageNum ? 'pagination__item--active' : '' ?>">
                <a class="pagination__link"
                   href="<?= escape($url->current(['p' => $pageNum == 1 ? null : $pageNum])) ?>">
                    <?= escape($pageLabel) ?>
                </a>
            </li>
        <?php } ?>
        <li class="pagination__item pagination__item--next <?= $currentPage === (int)$pageCount ? 'pagination__item--disabled' : '' ?>">
            <a class="pagination__link" href="<?= escape($url->current(['p' => $currentPage + 1])) ?>">
                <span class="icon icon-arrow-right"></span>
            </a>
        </li>
    </ul>
</nav>
