compiler:
  pool:
    magento:
      message: make run codes
      compiler: Lightna\Magento\App\Compiler\RunCodes
plugin:
  Lightna\Engine\App:
    - Lightna\Magento\App\Plugin\App
  Lightna\Engine\App\Scope:
    - Lightna\Magento\App\Plugin\App\Scope
  Lightna\Engine\App\Index\Changelog\Handler:
    - Lightna\Magento\App\Plugin\App\Index\Changelog\Handler
  Lightna\Session\App\Session\Cookie:
    - Lightna\Magento\App\Plugin\App\Session\Cookie
  Lightna\Engine\App\Update\Schema\Index\Triggers:
    - Lightna\Magento\App\Plugin\App\Update\Schema\Index\Triggers
