<?php
/**
 * Import:
 * @var Lightna\Magento\Backend\Data\Product $product
 */
$imageCount = count($product->gallery);
?>
<div class="gallery-grid cjs-gallery">
    <div class="gallery-thumbnails-container">
        <div class="gallery-thumbnails">
            <?php foreach ($product->gallery as $image) { ?>
                <div class="gallery-thumbnail">
                    <img src="<?= $image->thumbnail() ?>" width="100" height="124"
                         alt="" loading="lazy">
                </div>
            <?php } ?>
        </div>
        <div class="gallery-thumbnails-arrow previous disabled">
            <span class="icon icon-chevron-up"></span>
        </div>
        <div class="gallery-thumbnails-arrow next disabled">
            <span class="icon icon-chevron-down"></span>
        </div>
    </div>
    <div class="gallery-preview">
        <div class="gallery-slider">
            <?php foreach ($product->gallery as $index => $image) { ?>
                <div class="gallery-slide">
                    <img src="<?= $image->preview() ?>" width="535" height="664"
                         alt="<?= $product->name() ?>"
                         loading="<?= $index > 0 ? 'lazy' : 'eager' ?>">
                </div>
            <?php } ?>
        </div>
        <div class="gallery-arrow previous disabled hidden">
            <span class="icon icon-arrow-left"></span>
        </div>
        <div class="gallery-arrow next hidden">
            <span class="icon icon-arrow-right"></span>
        </div>
    </div>
    <?php if ($imageCount > 1) { ?>
        <div class="gallery-progress-bar">
            <div class="gallery-progress"></div>
        </div>
    <?php } ?>
</div>
