<?php
/**
 * Import:
 * @var Lightna\Engine\Data\Block $block
 * @var Lightna\Magento\Data\Product $product
 * @var Lightna\Magento\Data\Currency $currency
 */
?>
<div <?= $block->attributes() ?>>
    <?php if ($product->price->discount > 0): ?>
        <span class="price old-price"><?= $currency->render($product->price->regular) ?></span>
        <span class="price special-price"><?= $currency->render($product->price->final) ?></span>
    <?php else: ?>
        <span class="price regular-price"><?= $currency->render($product->price->final) ?></span>
    <?php endif; ?>
</div>
