<?php
/**
 * Import:
 * @var Lightna\Magento\Backend\Data\Product\Related $related
 */
if (count($related->products) === 0) {
    return;
}
?>
<div class="related-products">
    <div class="related-products__title"><?= phrase('Related Products') ?></div>
    <ul class="products-grid--wide">
        <?php foreach ($related->products as $index => $product): ?>
            <?= block('item', compact('index', 'product')) ?>
        <?php endforeach; ?>
    </ul>
</div>
