<?php
/**
 * Import:
 * @var Lightna\Magento\Backend\Data\Product $product
 * @var Lightna\Magento\Backend\Data\Session $session
 */
$wishlistItems = $session->wishlist->items;
$inWishlist = isset($wishlistItems[$product->entityId()]);
?>
<?php if ($inWishlist): ?>
    <div class="wishlist__button added"
         data-click-action="wishlist-remove"
         data-item-id="<?= $wishlistItems[$product->entityId()]->id() ?>">
        <span class="wishlist__icon"></span>
    </div>
<?php else: ?>
    <div class="wishlist__button"
         data-click-action="wishlist-add"
         data-product-id="<?= $product->entityId() ?>">
        <span class="wishlist__icon"></span>
    </div>
<?php endif; ?>
