plugin:
  Lightna\Engine\App\Context:
    - Lightna\Magento\App\Plugin\Context
router.bypass.rules.url_starts_with:
  - checkout/
  - customer/
  - sales/
  - wishlist/
  - downloadable/customer/products/
  - newsletter/manage/
  - vault/cards/listaction/
  - review/customer/
  - newsletter/
  - catalogsearch/
  - search/ajax/suggest
