<?php
/** @var Lightna\Magento\Data\Session $session */
$isLoggedIn = $session->user->groupId !== 0;
$iconClass = $isLoggedIn ? 'icon-user__filled' : 'icon-user__outline';
?>
<div class="icon-dropdown dropdown">
    <div class="header__icon header__icon--hover">
        <a href="/customer/account" class="icon <?= $iconClass ?>"></a>
    </div>
    <?php if ($isLoggedIn): ?>
        <?= block('customer') ?>
    <?php else: ?>
        <?= block('guest') ?>
    <?php endif; ?>
</div>
