<?php
/**
 * Import:
 * @var Lightna\Magento\Backend\Data\Product $product
 * @var Lightna\Engine\Data\Block $block
 */
$maxPlaceholderItems = min(count($product->related), $block->max);
?>
<div <?= $block->attributes() ?>>
    <ul class="products-grid--wide">
        <?php for ($i = 0; $i < $maxPlaceholderItems; $i++): ?>
            <li class="product-tile__placeholder"></li>
        <?php endfor; ?>
    </ul>
</div>
