extends:
  - page
.head:
  attributes:
    prefix: "og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# product: http://ogp.me/ns/product#"
  .link:
    .product:
      template: lightna/magento-frontend/page/head/link/style/product.phtml
.body:
  attributes:
    class:
      - product
  .main:
    .breadcrumbs:
      id: breadcrumbs
      template: lightna/magento-frontend/product/breadcrumbs.phtml
    .content:
      container: div
      attributes:
        class:
          - grid
          - gap-6
          - lg:gap-x-20
          - md:gap-8
          - md:grid-cols-[auto_40%]
          - items-start
      .left-container:
        container: div
        attributes:
          class:
            - relative
        .gallery:
          id: image-gallery
          template: lightna/magento-frontend/product/gallery.phtml
          image:
            preview:
              width: 535
              height: 664
            thumbnail:
              width: 100
              height: 124
      .right-container:
        container: div
        attributes:
          class:
            - md:sticky
            - top-[88px]
        .sku:
          id: product-sku
          template: lightna/magento-frontend/product/attributes/sku.phtml
        .name:
          id: product-name
          template: lightna/magento-frontend/product/attributes/name.phtml
        .price-and-discount:
          container: div
          attributes:
            class:
              - flex
              - items-center
              - gap-x-3
              - gap-y-1
              - flex-wrap-reverse
              - pb-2
              - mb-4
              - price-lg
          .price:
            id: product-price
            template: lightna/magento-frontend/component/product/price.phtml
            attributes:
              class:
                - flex
                - items-center
                - flex-wrap
                - gap-x-3
                - gap-y-1
          .discount:
            id: product-discount
            template: lightna/magento-frontend/component/product/discount.phtml
        .cta:
          .add-to-cart:
            id: product-add-to-cart
            template: lightna/magento-frontend/product/cta/add-to-cart.phtml
            attributes:
              class:
                - cjs-add-to-cart
                - flex
                - flex-wrap
                - gap-4
            .options:
              id: product-options
              type: dynamic
              template: lightna/magento-frontend/product/options.phtml
              attributes:
                class:
                  - cjs-product-options
                  - w-full
                  - flex
                  - flex-col
                  - gap-2
            .wishlist:
              id: wishlist-button
              private: true
              template: lightna/magento-frontend/product/wishlist.phtml
        .stock:
          id: product-stock
          template: lightna/magento-frontend/product/stock.phtml
        .usp:
          id: product-usp
          template: lightna/magento-frontend/product/usp.phtml
      .details:
        id: product-details
        template: lightna/magento-frontend/product/tabs.phtml
        .description:
          id: product-description
          title: "Description"
          active: true
          template: lightna/magento-frontend/product/description.phtml
        .specifications:
          id: product-specifications
          title: "Specifications"
          template: lightna/magento-frontend/product/attributes/all-visible.phtml
    .related-products:
      id: related-products
      template: lightna/magento-frontend/product/related.phtml
      .item: component/product/tile.yaml
