<?php
/**
 * Import:
 * @var Lightna\Magento\Backend\Data\Product $product
 * @var int $index
 */
?>
<?php $mainImage = reset($product->gallery) ?>
<a class="block" href="<?= $product->url() ?>" title="<?= $product->name() ?>">
    <img class="product-tile__image"
         loading="<?= $index > 2 ? 'lazy' : 'eager' ?>"
         width="285" height="354"
         src="<?= $mainImage->tile() ?>" alt="<?= $product->name() ?>">
</a>
