<?php
/** @var Lightna\Magento\Data\Config $config */

$ga = $config->ga;
if (!$ga->active || !$ga->account) {
    return;
}
?>
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?<?= $ga->account('url-param') ?>"></script>
<script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', <?= $ga->account('json-js') ?>);
</script>
