#!/usr/bin/env php
<?php
/** @var array $config */

declare(strict_types=1);

use Lightna\Engine\App\Cli;
use Lightna\Engine\App\Console\Compile;
use Lightna\Engine\App\UserException;

require __DIR__ . '/App/lib/cli.php';

$config = require LIGHTNA_ENTRY . 'config.php';
$command = $argv[1] ?? '';

if (in_array($command, ['?', 'help', '', '-h', '--help'])) {
    $commands = array_keys(cli_get_all_commands($config['compiler']['dir']));
    echo "  Commands list:\n    " . implode("\n    ", $commands) . "\n";
    exit;
}

if ($command === 'compile') {
    cli_init_compiler_without_autoload();
    (new Compile())->run();
    exit;
}

require __DIR__ . '/App/boot.php';

try {
    getobj(Cli::class)->run($command);
    echo "\n";
} catch (UserException $e) {
    echo cli_error($e->getMessage());
    echo "\n";
    exit(1);
}
