#!/usr/bin/env php
<?php
/** @var array $config */

declare(strict_types=1);

use Lightna\Engine\App\Cli;
use Lightna\Engine\App\Console\Compile;
use Lightna\Engine\App\UserException;

require __DIR__ . '/App/lib/cli.php';

$config = require LIGHTNA_ENTRY . 'config.php';
$command = $argv[1] ?? '';

if (in_array($command, ['?', 'help', '', '-h', '--help'])) {
    $commands = array_keys(cli_get_all_commands($config['compiler']['dir']));
    echo "\n Available commands:\n\n    " . implode("\n    ", $commands) . "\n\n";
    exit;
}

if (str_starts_with($command, 'build.')) {
    define('IS_COMPILER', true);
}

if (in_array($command, ['build.compile', 'build.apply'])) {
    cli_init_compiler();
    if ($command === 'build.compile') {
        (new Compile())->run();
    } elseif ($command === 'build.apply') {
        (new Compile())->apply();
    }
    exit;
}

require_once __DIR__ . '/App/boot.php';

try {
    getobj(Cli::class)->run($command);
} catch (UserException $e) {
    echo cli_error($e->getMessage()) . "\n";
    exit(1);
}
