<?php
/**
 * Import:
 * @var Lightna\Engine\Data\Block $block
 * @var Lightna\Magento\Backend\Data\Product $product
 */
?>
<div <?= $block->attributes() ?> data-product-id="<?= $product->entityId() ?>">
    <?= block('options') ?>
    <div class="product-actions-row">
        <button type="button" class="btn-cart" data-click-action="add-to-cart">
            <span><?= phrase('Add to Cart') ?></span>
        </button>
        <?= block('wishlist') ?>
    </div>
</div>
